version: '3'
services:
  my-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5050-5055:5050
    volumes:
      - ${VOLUME}:/home/app/
    environment:
      - DEBUG=${DEBUG}
    deploy:
      replicas: 3

volumes:
  production_volume:
  staging_volume: